{ config, pkgs, ... }:

{
  # Basic system configuration
  imports = [
    ./hardware-configuration.nix # Autogenerated by NixOS installer
  ];
  system.stateVersion = "24.05";
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/xvda";

  # Set your timezone
  time.timeZone = "UTC";
  # Enable SSH for remote access

  programs.ssh.startAgent = true;

  virtualisation.docker.enable = true;

  # Create a default user for development from the common user
  user = import ../common/user.nix;

  users.users.vcoates = user;

  # Enable sudo for wheel group
  security.sudo = {
    enable = true;
    wheelNeedsPassword = false;
  };

  basePkgs = import ../common/packages.nix { pkgs = pkgs; };

  # Set up development tools and utilities
  environment.systemPackages = [
    evil-helix
    zellij
  ] ++ basePkgs;

  # Firewall configuration
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 80 443 ]; # Open ports for SSH, HTTP, and HTTPS
  };

  # Set up a basic Nix cache to speed up package installations
  nix.settings = {
    trusted-users = [ "root" "vcoates" ];
    binary-caches = [ "https://cache.nixos.org" ];
    experimental-features = [ "nix-command" "flakes" ];
  };

  # Miscellaneous tweaks
  environment.variables = {
    EDITOR = "vim"; # Set default editor
    PAGER = "less"; # Set default pager
  };

}
